/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155__factory } from "./ERC1155__factory";
export { ERC165__factory } from "./ERC165__factory";
export { Hogwarts__factory } from "./Hogwarts__factory";
export { IERC1155__factory } from "./IERC1155__factory";
export { IERC1155MetadataURI__factory } from "./IERC1155MetadataURI__factory";
export { IERC1155Receiver__factory } from "./IERC1155Receiver__factory";
export { IERC165__factory } from "./IERC165__factory";
export { Ownable__factory } from "./Ownable__factory";
