/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155 } from "./ERC1155";
export type { ERC165 } from "./ERC165";
export type { Hogwarts } from "./Hogwarts";
export type { IERC1155 } from "./IERC1155";
export type { IERC1155MetadataURI } from "./IERC1155MetadataURI";
export type { IERC1155Receiver } from "./IERC1155Receiver";
export type { IERC165 } from "./IERC165";
export type { Ownable } from "./Ownable";
