/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as hogwartsSol from "./Hogwarts.sol";
export type { hogwartsSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export type { ERC1155 } from "./Hogwarts.sol/ERC1155";
export { ERC1155__factory } from "./factories/Hogwarts.sol/ERC1155__factory";
export type { ERC165 } from "./Hogwarts.sol/ERC165";
export { ERC165__factory } from "./factories/Hogwarts.sol/ERC165__factory";
export type { Hogwarts } from "./Hogwarts.sol/Hogwarts";
export { Hogwarts__factory } from "./factories/Hogwarts.sol/Hogwarts__factory";
export type { IERC1155 } from "./Hogwarts.sol/IERC1155";
export { IERC1155__factory } from "./factories/Hogwarts.sol/IERC1155__factory";
export type { IERC1155MetadataURI } from "./Hogwarts.sol/IERC1155MetadataURI";
export { IERC1155MetadataURI__factory } from "./factories/Hogwarts.sol/IERC1155MetadataURI__factory";
export type { IERC1155Receiver } from "./Hogwarts.sol/IERC1155Receiver";
export { IERC1155Receiver__factory } from "./factories/Hogwarts.sol/IERC1155Receiver__factory";
export type { IERC165 } from "./Hogwarts.sol/IERC165";
export { IERC165__factory } from "./factories/Hogwarts.sol/IERC165__factory";
export type { Ownable } from "./Hogwarts.sol/Ownable";
export { Ownable__factory } from "./factories/Hogwarts.sol/Ownable__factory";
export { Lock__factory } from "./factories/Lock__factory";
