version: '3.7'

services:

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: discordtokengate
    networks:
      - mongo-compose-network
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    restart: unless-stopped

  mongodb-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
      - ME_CONFIG_MONGODB_URL=mongodb://root:rootpassword@mongo:27017
      - ME_CONFIG_BASICAUTH_USERNAME=meuser
      - ME_CONFIG_BASICAUTH_PASSWORD=mepassword
    networks:
      - mongo-compose-network
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    restart: unless-stopped
  # serverless-api:
  #   build: .
  #   image: discordtokengate/serverless-api
  #   container_name: serverless
  #   environment:
  #     # The name of the localstack container is host for dynamodb
  #     AWS_ENDPOINT: 'mongodb://root:rootpassword@mongo:27017'
  #     AWS_REGION: 'us-east-1'
  #     # leaving these blank will try and read from the terminal
  #     AWS_ACCESS_KEY_ID:
  #     AWS_SECRET_ACCESS_KEY:
  #   networks:
  #     - mongo-compose-network
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped

networks:
  mongo-compose-network:
    driver: bridge
