name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        working-directory: docs
        run: npm ci

      - name: Build
        working-directory: docs
        run: |
          npm run build
          npm run export
        env:
          NEXT_PUBLIC_BASE_PATH: /token-gating-discord-bot-api

      - name: Add .nojekyll files
        run: |
          # Add .nojekyll to root
          touch .nojekyll
          # Add .nojekyll to docs
          touch docs/.nojekyll
          # Add .nojekyll to build output
          touch docs/out/.nojekyll
          # Copy build files to docs
          cp -r docs/out/* docs/
          rm -rf docs/out

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          clean: true